/**
 * generated by Xtext 2.12.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.TowerDefenseRuntimeModule;
import xtext.TowerDefenseStandaloneSetup;
import xtext.ide.TowerDefenseIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TowerDefenseIdeSetup extends TowerDefenseStandaloneSetup {
  @Override
  public Injector createInjector() {
    TowerDefenseRuntimeModule _towerDefenseRuntimeModule = new TowerDefenseRuntimeModule();
    TowerDefenseIdeModule _towerDefenseIdeModule = new TowerDefenseIdeModule();
    return Guice.createInjector(Modules2.mixin(_towerDefenseRuntimeModule, _towerDefenseIdeModule));
  }
}
