/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import xtext.towerDefense.Energie;
import xtext.towerDefense.TowerDefenseFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Energie</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class EnergieTest extends TestCase {

	/**
	 * The fixture for this Energie test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Energie fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(EnergieTest.class);
	}

	/**
	 * Constructs a new Energie test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EnergieTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Energie test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Energie fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Energie test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Energie getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(TowerDefenseFactory.eINSTANCE.createEnergie());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //EnergieTest
