/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import xtext.towerDefense.PartieElement;
import xtext.towerDefense.TowerDefenseFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Partie Element</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class PartieElementTest extends TestCase {

	/**
	 * The fixture for this Partie Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartieElement fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(PartieElementTest.class);
	}

	/**
	 * Constructs a new Partie Element test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PartieElementTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Partie Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(PartieElement fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Partie Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartieElement getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(TowerDefenseFactory.eINSTANCE.createPartieElement());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //PartieElementTest
