/*
 * generated by Xtext 2.12.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.TowerDefense.ui.internal.TowerDefenseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TowerDefenseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TowerDefenseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TowerDefenseActivator.getInstance().getInjector(TowerDefenseActivator.XTEXT_TOWERDEFENSE);
	}
	
}
