/**
 * generated by Xtext 2.12.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.ui.AbstractTowerDefenseUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TowerDefenseUiModule extends AbstractTowerDefenseUiModule {
  public TowerDefenseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
