/*
 * generated by Xtext 2.12.0
 */
package xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TowerDefenseRuntimeModule extends AbstractTowerDefenseRuntimeModule {
}
