/*
 * generated by Xtext 2.12.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.TowerDefense.ui.internal.TowerDefenseActivator;

public class TowerDefenseUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TowerDefenseActivator.getInstance().getInjector("xtext.TowerDefense");
	}

}
