/*
 * generated by Xtext 2.12.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalTowerDefenseParser;
import xtext.services.TowerDefenseGrammarAccess;

public class TowerDefenseParser extends AbstractAntlrParser {

	@Inject
	private TowerDefenseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTowerDefenseParser createParser(XtextTokenStream stream) {
		return new InternalTowerDefenseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Jeu";
	}

	public TowerDefenseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TowerDefenseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
