/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carte</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.towerDefense.Carte#getName <em>Name</em>}</li>
 *   <li>{@link xtext.towerDefense.Carte#getNbLignes <em>Nb Lignes</em>}</li>
 *   <li>{@link xtext.towerDefense.Carte#getNbColonnes <em>Nb Colonnes</em>}</li>
 *   <li>{@link xtext.towerDefense.Carte#getCases <em>Cases</em>}</li>
 * </ul>
 *
 * @see xtext.towerDefense.TowerDefensePackage#getCarte()
 * @model
 * @generated
 */
public interface Carte extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see xtext.towerDefense.TowerDefensePackage#getCarte_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link xtext.towerDefense.Carte#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Nb Lignes</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nb Lignes</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Nb Lignes</em>' attribute.
	 * @see #setNbLignes(int)
	 * @see xtext.towerDefense.TowerDefensePackage#getCarte_NbLignes()
	 * @model
	 * @generated
	 */
  int getNbLignes();

  /**
	 * Sets the value of the '{@link xtext.towerDefense.Carte#getNbLignes <em>Nb Lignes</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Nb Lignes</em>' attribute.
	 * @see #getNbLignes()
	 * @generated
	 */
  void setNbLignes(int value);

  /**
	 * Returns the value of the '<em><b>Nb Colonnes</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nb Colonnes</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Nb Colonnes</em>' attribute.
	 * @see #setNbColonnes(int)
	 * @see xtext.towerDefense.TowerDefensePackage#getCarte_NbColonnes()
	 * @model
	 * @generated
	 */
  int getNbColonnes();

  /**
	 * Sets the value of the '{@link xtext.towerDefense.Carte#getNbColonnes <em>Nb Colonnes</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Nb Colonnes</em>' attribute.
	 * @see #getNbColonnes()
	 * @generated
	 */
  void setNbColonnes(int value);

  /**
	 * Returns the value of the '<em><b>Cases</b></em>' reference list.
	 * The list contents are of type {@link xtext.towerDefense.Case}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cases</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Cases</em>' reference list.
	 * @see xtext.towerDefense.TowerDefensePackage#getCarte_Cases()
	 * @model
	 * @generated
	 */
  EList<Case> getCases();

} // Carte
