/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.towerDefense.Case#getI <em>I</em>}</li>
 *   <li>{@link xtext.towerDefense.Case#getJ <em>J</em>}</li>
 *   <li>{@link xtext.towerDefense.Case#getNatureTerrain <em>Nature Terrain</em>}</li>
 * </ul>
 *
 * @see xtext.towerDefense.TowerDefensePackage#getCase()
 * @model
 * @generated
 */
public interface Case extends EObject
{
  /**
   * Returns the value of the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' attribute.
   * @see #setI(int)
   * @see xtext.towerDefense.TowerDefensePackage#getCase_I()
   * @model
   * @generated
   */
  int getI();

  /**
   * Sets the value of the '{@link xtext.towerDefense.Case#getI <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' attribute.
   * @see #getI()
   * @generated
   */
  void setI(int value);

  /**
   * Returns the value of the '<em><b>J</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>J</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>J</em>' attribute.
   * @see #setJ(int)
   * @see xtext.towerDefense.TowerDefensePackage#getCase_J()
   * @model
   * @generated
   */
  int getJ();

  /**
   * Sets the value of the '{@link xtext.towerDefense.Case#getJ <em>J</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>J</em>' attribute.
   * @see #getJ()
   * @generated
   */
  void setJ(int value);

  /**
   * Returns the value of the '<em><b>Nature Terrain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nature Terrain</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nature Terrain</em>' containment reference.
   * @see #setNatureTerrain(NatureTerrain)
   * @see xtext.towerDefense.TowerDefensePackage#getCase_NatureTerrain()
   * @model containment="true"
   * @generated
   */
  NatureTerrain getNatureTerrain();

  /**
   * Sets the value of the '{@link xtext.towerDefense.Case#getNatureTerrain <em>Nature Terrain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nature Terrain</em>' containment reference.
   * @see #getNatureTerrain()
   * @generated
   */
  void setNatureTerrain(NatureTerrain value);

} // Case
