/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.towerDefense.TowerDefenseFactory
 * @model kind="package"
 * @generated
 */
public interface TowerDefensePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "towerDefense";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.TowerDefense.xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "towerDefense";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TowerDefensePackage eINSTANCE = xtext.towerDefense.impl.TowerDefensePackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.JeuImpl <em>Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.JeuImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getJeu()
   * @generated
   */
  int JEU = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Parties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU__PARTIES = 1;

  /**
   * The number of structural features of the '<em>Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JEU_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.PartieImpl <em>Partie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.PartieImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getPartie()
   * @generated
   */
  int PARTIE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE__NAME = 0;

  /**
   * The feature id for the '<em><b>Parties Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE__PARTIES_ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Niveaux</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE__NIVEAUX = 2;

  /**
   * The number of structural features of the '<em>Partie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.PartieElementImpl <em>Partie Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.PartieElementImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getPartieElement()
   * @generated
   */
  int PARTIE_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Obstacle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_ELEMENT__OBSTACLE = 0;

  /**
   * The feature id for the '<em><b>Mobile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_ELEMENT__MOBILE = 1;

  /**
   * The feature id for the '<em><b>Projectile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_ELEMENT__PROJECTILE = 2;

  /**
   * The feature id for the '<em><b>Nature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_ELEMENT__NATURE = 3;

  /**
   * The number of structural features of the '<em>Partie Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIE_ELEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.EnergieImpl <em>Energie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.EnergieImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getEnergie()
   * @generated
   */
  int ENERGIE = 3;

  /**
   * The feature id for the '<em><b>Infini</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGIE__INFINI = 0;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGIE__VALEUR = 1;

  /**
   * The number of structural features of the '<em>Energie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENERGIE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.ObstacleImpl <em>Obstacle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.ObstacleImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getObstacle()
   * @generated
   */
  int OBSTACLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Campement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__CAMPEMENT = 1;

  /**
   * The feature id for the '<em><b>Quantite Energie Max</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__QUANTITE_ENERGIE_MAX = 2;

  /**
   * The feature id for the '<em><b>Quantite Energie Courant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__QUANTITE_ENERGIE_COURANT = 3;

  /**
   * The feature id for the '<em><b>Ponts Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__PONTS_ACTION = 4;

  /**
   * The feature id for the '<em><b>Tactique</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE__TACTIQUE = 5;

  /**
   * The number of structural features of the '<em>Obstacle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.TactiqueImpl <em>Tactique</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.TactiqueImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTactique()
   * @generated
   */
  int TACTIQUE = 5;

  /**
   * The feature id for the '<em><b>Proche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TACTIQUE__PROCHE = 0;

  /**
   * The feature id for the '<em><b>Faible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TACTIQUE__FAIBLE = 1;

  /**
   * The feature id for the '<em><b>Fort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TACTIQUE__FORT = 2;

  /**
   * The number of structural features of the '<em>Tactique</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TACTIQUE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.MobileImpl <em>Mobile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.MobileImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getMobile()
   * @generated
   */
  int MOBILE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__NAME = 0;

  /**
   * The feature id for the '<em><b>Force</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__FORCE = 1;

  /**
   * The feature id for the '<em><b>Volume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__VOLUME = 2;

  /**
   * The feature id for the '<em><b>Num Vague</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__NUM_VAGUE = 3;

  /**
   * The feature id for the '<em><b>Case Entree</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__CASE_ENTREE = 4;

  /**
   * The feature id for the '<em><b>Case Sortie</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__CASE_SORTIE = 5;

  /**
   * The feature id for the '<em><b>Quantite Energie Max</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__QUANTITE_ENERGIE_MAX = 6;

  /**
   * The feature id for the '<em><b>Quantite Energie Courant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__QUANTITE_ENERGIE_COURANT = 7;

  /**
   * The feature id for the '<em><b>Points Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE__POINTS_ACTION = 8;

  /**
   * The number of structural features of the '<em>Mobile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOBILE_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.ProjectileImpl <em>Projectile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.ProjectileImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getProjectile()
   * @generated
   */
  int PROJECTILE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__NAME = 0;

  /**
   * The feature id for the '<em><b>Portee</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__PORTEE = 1;

  /**
   * The feature id for the '<em><b>Masse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__MASSE = 2;

  /**
   * The feature id for the '<em><b>Vitesse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__VITESSE = 3;

  /**
   * The feature id for the '<em><b>Case</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__CASE = 4;

  /**
   * The feature id for the '<em><b>Cible</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__CIBLE = 5;

  /**
   * The feature id for the '<em><b>Degat</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE__DEGAT = 6;

  /**
   * The number of structural features of the '<em>Projectile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTILE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.NatureTerrainImpl <em>Nature Terrain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.NatureTerrainImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getNatureTerrain()
   * @generated
   */
  int NATURE_TERRAIN = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NATURE_TERRAIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Volume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NATURE_TERRAIN__VOLUME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NATURE_TERRAIN__TYPE = 2;

  /**
   * The feature id for the '<em><b>Fatigue</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NATURE_TERRAIN__FATIGUE = 3;

  /**
   * The number of structural features of the '<em>Nature Terrain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NATURE_TERRAIN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.NiveauImpl <em>Niveau</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.NiveauImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getNiveau()
   * @generated
   */
  int NIVEAU = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__NAME = 0;

  /**
   * The feature id for the '<em><b>Difficulte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__DIFFICULTE = 1;

  /**
   * The feature id for the '<em><b>Duree Pause</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__DUREE_PAUSE = 2;

  /**
   * The feature id for the '<em><b>Argent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__ARGENT = 3;

  /**
   * The feature id for the '<em><b>Mob Sortis Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__MOB_SORTIS_LIMITE = 4;

  /**
   * The feature id for the '<em><b>Terrain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__TERRAIN = 5;

  /**
   * The feature id for the '<em><b>Vagues</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU__VAGUES = 6;

  /**
   * The number of structural features of the '<em>Niveau</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NIVEAU_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.TerrainDeJeuImpl <em>Terrain De Jeu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.TerrainDeJeuImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTerrainDeJeu()
   * @generated
   */
  int TERRAIN_DE_JEU = 10;

  /**
   * The feature id for the '<em><b>Damier</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRAIN_DE_JEU__DAMIER = 0;

  /**
   * The number of structural features of the '<em>Terrain De Jeu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRAIN_DE_JEU_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.DamierImpl <em>Damier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.DamierImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getDamier()
   * @generated
   */
  int DAMIER = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMIER__NAME = 0;

  /**
   * The feature id for the '<em><b>Nb Lignes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMIER__NB_LIGNES = 1;

  /**
   * The feature id for the '<em><b>Nb Colonnes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMIER__NB_COLONNES = 2;

  /**
   * The feature id for the '<em><b>Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMIER__CASES = 3;

  /**
   * The number of structural features of the '<em>Damier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMIER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.CaseImpl <em>Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.CaseImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getCase()
   * @generated
   */
  int CASE = 12;

  /**
   * The feature id for the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__I = 0;

  /**
   * The feature id for the '<em><b>J</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__J = 1;

  /**
   * The feature id for the '<em><b>Nature Terrain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__NATURE_TERRAIN = 2;

  /**
   * The number of structural features of the '<em>Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.towerDefense.impl.VagueImpl <em>Vague</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.impl.VagueImpl
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getVague()
   * @generated
   */
  int VAGUE = 13;

  /**
   * The feature id for the '<em><b>Mobiles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAGUE__MOBILES = 0;

  /**
   * The feature id for the '<em><b>Obstacles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAGUE__OBSTACLES = 1;

  /**
   * The feature id for the '<em><b>Gain Victoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAGUE__GAIN_VICTOIRE = 2;

  /**
   * The number of structural features of the '<em>Vague</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAGUE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.towerDefense.TYPE_TERRAIN <em>TYPE TERRAIN</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.TYPE_TERRAIN
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTYPE_TERRAIN()
   * @generated
   */
  int TYPE_TERRAIN = 14;

  /**
   * The meta object id for the '{@link xtext.towerDefense.Difficulte <em>Difficulte</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.towerDefense.Difficulte
   * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getDifficulte()
   * @generated
   */
  int DIFFICULTE = 15;


  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Jeu <em>Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jeu</em>'.
   * @see xtext.towerDefense.Jeu
   * @generated
   */
  EClass getJeu();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Jeu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Jeu#getName()
   * @see #getJeu()
   * @generated
   */
  EAttribute getJeu_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.towerDefense.Jeu#getParties <em>Parties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parties</em>'.
   * @see xtext.towerDefense.Jeu#getParties()
   * @see #getJeu()
   * @generated
   */
  EReference getJeu_Parties();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Partie <em>Partie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Partie</em>'.
   * @see xtext.towerDefense.Partie
   * @generated
   */
  EClass getPartie();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Partie#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Partie#getName()
   * @see #getPartie()
   * @generated
   */
  EAttribute getPartie_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.towerDefense.Partie#getPartiesElements <em>Parties Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parties Elements</em>'.
   * @see xtext.towerDefense.Partie#getPartiesElements()
   * @see #getPartie()
   * @generated
   */
  EReference getPartie_PartiesElements();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.towerDefense.Partie#getNiveaux <em>Niveaux</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Niveaux</em>'.
   * @see xtext.towerDefense.Partie#getNiveaux()
   * @see #getPartie()
   * @generated
   */
  EReference getPartie_Niveaux();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.PartieElement <em>Partie Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Partie Element</em>'.
   * @see xtext.towerDefense.PartieElement
   * @generated
   */
  EClass getPartieElement();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.PartieElement#getObstacle <em>Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obstacle</em>'.
   * @see xtext.towerDefense.PartieElement#getObstacle()
   * @see #getPartieElement()
   * @generated
   */
  EAttribute getPartieElement_Obstacle();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.PartieElement#getMobile <em>Mobile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mobile</em>'.
   * @see xtext.towerDefense.PartieElement#getMobile()
   * @see #getPartieElement()
   * @generated
   */
  EAttribute getPartieElement_Mobile();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.PartieElement#getProjectile <em>Projectile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Projectile</em>'.
   * @see xtext.towerDefense.PartieElement#getProjectile()
   * @see #getPartieElement()
   * @generated
   */
  EAttribute getPartieElement_Projectile();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.PartieElement#getNature <em>Nature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nature</em>'.
   * @see xtext.towerDefense.PartieElement#getNature()
   * @see #getPartieElement()
   * @generated
   */
  EAttribute getPartieElement_Nature();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Energie <em>Energie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Energie</em>'.
   * @see xtext.towerDefense.Energie
   * @generated
   */
  EClass getEnergie();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Energie#isInfini <em>Infini</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Infini</em>'.
   * @see xtext.towerDefense.Energie#isInfini()
   * @see #getEnergie()
   * @generated
   */
  EAttribute getEnergie_Infini();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Energie#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see xtext.towerDefense.Energie#getValeur()
   * @see #getEnergie()
   * @generated
   */
  EAttribute getEnergie_Valeur();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Obstacle <em>Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obstacle</em>'.
   * @see xtext.towerDefense.Obstacle
   * @generated
   */
  EClass getObstacle();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Obstacle#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Obstacle#getName()
   * @see #getObstacle()
   * @generated
   */
  EAttribute getObstacle_Name();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Obstacle#getCampement <em>Campement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Campement</em>'.
   * @see xtext.towerDefense.Obstacle#getCampement()
   * @see #getObstacle()
   * @generated
   */
  EReference getObstacle_Campement();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Obstacle#getQuantiteEnergieMax <em>Quantite Energie Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Quantite Energie Max</em>'.
   * @see xtext.towerDefense.Obstacle#getQuantiteEnergieMax()
   * @see #getObstacle()
   * @generated
   */
  EReference getObstacle_QuantiteEnergieMax();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Obstacle#getQuantiteEnergieCourant <em>Quantite Energie Courant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Quantite Energie Courant</em>'.
   * @see xtext.towerDefense.Obstacle#getQuantiteEnergieCourant()
   * @see #getObstacle()
   * @generated
   */
  EReference getObstacle_QuantiteEnergieCourant();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Obstacle#getPontsAction <em>Ponts Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ponts Action</em>'.
   * @see xtext.towerDefense.Obstacle#getPontsAction()
   * @see #getObstacle()
   * @generated
   */
  EReference getObstacle_PontsAction();

  /**
   * Returns the meta object for the containment reference '{@link xtext.towerDefense.Obstacle#getTactique <em>Tactique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tactique</em>'.
   * @see xtext.towerDefense.Obstacle#getTactique()
   * @see #getObstacle()
   * @generated
   */
  EReference getObstacle_Tactique();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Tactique <em>Tactique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tactique</em>'.
   * @see xtext.towerDefense.Tactique
   * @generated
   */
  EClass getTactique();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Tactique#getProche <em>Proche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proche</em>'.
   * @see xtext.towerDefense.Tactique#getProche()
   * @see #getTactique()
   * @generated
   */
  EAttribute getTactique_Proche();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Tactique#getFaible <em>Faible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Faible</em>'.
   * @see xtext.towerDefense.Tactique#getFaible()
   * @see #getTactique()
   * @generated
   */
  EAttribute getTactique_Faible();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Tactique#getFort <em>Fort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fort</em>'.
   * @see xtext.towerDefense.Tactique#getFort()
   * @see #getTactique()
   * @generated
   */
  EAttribute getTactique_Fort();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Mobile <em>Mobile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mobile</em>'.
   * @see xtext.towerDefense.Mobile
   * @generated
   */
  EClass getMobile();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Mobile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Mobile#getName()
   * @see #getMobile()
   * @generated
   */
  EAttribute getMobile_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Mobile#getForce <em>Force</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Force</em>'.
   * @see xtext.towerDefense.Mobile#getForce()
   * @see #getMobile()
   * @generated
   */
  EAttribute getMobile_Force();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Mobile#getVolume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Volume</em>'.
   * @see xtext.towerDefense.Mobile#getVolume()
   * @see #getMobile()
   * @generated
   */
  EAttribute getMobile_Volume();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Mobile#getNumVague <em>Num Vague</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Vague</em>'.
   * @see xtext.towerDefense.Mobile#getNumVague()
   * @see #getMobile()
   * @generated
   */
  EAttribute getMobile_NumVague();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Mobile#getCaseEntree <em>Case Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Case Entree</em>'.
   * @see xtext.towerDefense.Mobile#getCaseEntree()
   * @see #getMobile()
   * @generated
   */
  EReference getMobile_CaseEntree();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Mobile#getCaseSortie <em>Case Sortie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Case Sortie</em>'.
   * @see xtext.towerDefense.Mobile#getCaseSortie()
   * @see #getMobile()
   * @generated
   */
  EReference getMobile_CaseSortie();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Mobile#getQuantiteEnergieMax <em>Quantite Energie Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Quantite Energie Max</em>'.
   * @see xtext.towerDefense.Mobile#getQuantiteEnergieMax()
   * @see #getMobile()
   * @generated
   */
  EReference getMobile_QuantiteEnergieMax();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Mobile#getQuantiteEnergieCourant <em>Quantite Energie Courant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Quantite Energie Courant</em>'.
   * @see xtext.towerDefense.Mobile#getQuantiteEnergieCourant()
   * @see #getMobile()
   * @generated
   */
  EReference getMobile_QuantiteEnergieCourant();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Mobile#getPointsAction <em>Points Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Points Action</em>'.
   * @see xtext.towerDefense.Mobile#getPointsAction()
   * @see #getMobile()
   * @generated
   */
  EReference getMobile_PointsAction();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Projectile <em>Projectile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Projectile</em>'.
   * @see xtext.towerDefense.Projectile
   * @generated
   */
  EClass getProjectile();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Projectile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Projectile#getName()
   * @see #getProjectile()
   * @generated
   */
  EAttribute getProjectile_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Projectile#getPortee <em>Portee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Portee</em>'.
   * @see xtext.towerDefense.Projectile#getPortee()
   * @see #getProjectile()
   * @generated
   */
  EAttribute getProjectile_Portee();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Projectile#getMasse <em>Masse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Masse</em>'.
   * @see xtext.towerDefense.Projectile#getMasse()
   * @see #getProjectile()
   * @generated
   */
  EAttribute getProjectile_Masse();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Projectile#getVitesse <em>Vitesse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vitesse</em>'.
   * @see xtext.towerDefense.Projectile#getVitesse()
   * @see #getProjectile()
   * @generated
   */
  EAttribute getProjectile_Vitesse();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Projectile#getCase <em>Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Case</em>'.
   * @see xtext.towerDefense.Projectile#getCase()
   * @see #getProjectile()
   * @generated
   */
  EReference getProjectile_Case();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Projectile#getCible <em>Cible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cible</em>'.
   * @see xtext.towerDefense.Projectile#getCible()
   * @see #getProjectile()
   * @generated
   */
  EReference getProjectile_Cible();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.Projectile#getDegat <em>Degat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Degat</em>'.
   * @see xtext.towerDefense.Projectile#getDegat()
   * @see #getProjectile()
   * @generated
   */
  EReference getProjectile_Degat();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.NatureTerrain <em>Nature Terrain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nature Terrain</em>'.
   * @see xtext.towerDefense.NatureTerrain
   * @generated
   */
  EClass getNatureTerrain();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.NatureTerrain#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.NatureTerrain#getName()
   * @see #getNatureTerrain()
   * @generated
   */
  EAttribute getNatureTerrain_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.NatureTerrain#getVolume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Volume</em>'.
   * @see xtext.towerDefense.NatureTerrain#getVolume()
   * @see #getNatureTerrain()
   * @generated
   */
  EAttribute getNatureTerrain_Volume();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.NatureTerrain#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see xtext.towerDefense.NatureTerrain#getType()
   * @see #getNatureTerrain()
   * @generated
   */
  EAttribute getNatureTerrain_Type();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.NatureTerrain#getFatigue <em>Fatigue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fatigue</em>'.
   * @see xtext.towerDefense.NatureTerrain#getFatigue()
   * @see #getNatureTerrain()
   * @generated
   */
  EReference getNatureTerrain_Fatigue();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Niveau <em>Niveau</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Niveau</em>'.
   * @see xtext.towerDefense.Niveau
   * @generated
   */
  EClass getNiveau();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Niveau#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Niveau#getName()
   * @see #getNiveau()
   * @generated
   */
  EAttribute getNiveau_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Niveau#getDifficulte <em>Difficulte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Difficulte</em>'.
   * @see xtext.towerDefense.Niveau#getDifficulte()
   * @see #getNiveau()
   * @generated
   */
  EAttribute getNiveau_Difficulte();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Niveau#getDureePause <em>Duree Pause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duree Pause</em>'.
   * @see xtext.towerDefense.Niveau#getDureePause()
   * @see #getNiveau()
   * @generated
   */
  EAttribute getNiveau_DureePause();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Niveau#getArgent <em>Argent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argent</em>'.
   * @see xtext.towerDefense.Niveau#getArgent()
   * @see #getNiveau()
   * @generated
   */
  EAttribute getNiveau_Argent();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Niveau#getMobSortisLimite <em>Mob Sortis Limite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mob Sortis Limite</em>'.
   * @see xtext.towerDefense.Niveau#getMobSortisLimite()
   * @see #getNiveau()
   * @generated
   */
  EAttribute getNiveau_MobSortisLimite();

  /**
   * Returns the meta object for the containment reference '{@link xtext.towerDefense.Niveau#getTerrain <em>Terrain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Terrain</em>'.
   * @see xtext.towerDefense.Niveau#getTerrain()
   * @see #getNiveau()
   * @generated
   */
  EReference getNiveau_Terrain();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.towerDefense.Niveau#getVagues <em>Vagues</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vagues</em>'.
   * @see xtext.towerDefense.Niveau#getVagues()
   * @see #getNiveau()
   * @generated
   */
  EReference getNiveau_Vagues();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.TerrainDeJeu <em>Terrain De Jeu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terrain De Jeu</em>'.
   * @see xtext.towerDefense.TerrainDeJeu
   * @generated
   */
  EClass getTerrainDeJeu();

  /**
   * Returns the meta object for the reference '{@link xtext.towerDefense.TerrainDeJeu#getDamier <em>Damier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Damier</em>'.
   * @see xtext.towerDefense.TerrainDeJeu#getDamier()
   * @see #getTerrainDeJeu()
   * @generated
   */
  EReference getTerrainDeJeu_Damier();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Damier <em>Damier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Damier</em>'.
   * @see xtext.towerDefense.Damier
   * @generated
   */
  EClass getDamier();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Damier#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.towerDefense.Damier#getName()
   * @see #getDamier()
   * @generated
   */
  EAttribute getDamier_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Damier#getNbLignes <em>Nb Lignes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb Lignes</em>'.
   * @see xtext.towerDefense.Damier#getNbLignes()
   * @see #getDamier()
   * @generated
   */
  EAttribute getDamier_NbLignes();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Damier#getNbColonnes <em>Nb Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb Colonnes</em>'.
   * @see xtext.towerDefense.Damier#getNbColonnes()
   * @see #getDamier()
   * @generated
   */
  EAttribute getDamier_NbColonnes();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.towerDefense.Damier#getCases <em>Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cases</em>'.
   * @see xtext.towerDefense.Damier#getCases()
   * @see #getDamier()
   * @generated
   */
  EReference getDamier_Cases();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Case <em>Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case</em>'.
   * @see xtext.towerDefense.Case
   * @generated
   */
  EClass getCase();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Case#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>I</em>'.
   * @see xtext.towerDefense.Case#getI()
   * @see #getCase()
   * @generated
   */
  EAttribute getCase_I();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Case#getJ <em>J</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>J</em>'.
   * @see xtext.towerDefense.Case#getJ()
   * @see #getCase()
   * @generated
   */
  EAttribute getCase_J();

  /**
   * Returns the meta object for the containment reference '{@link xtext.towerDefense.Case#getNatureTerrain <em>Nature Terrain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nature Terrain</em>'.
   * @see xtext.towerDefense.Case#getNatureTerrain()
   * @see #getCase()
   * @generated
   */
  EReference getCase_NatureTerrain();

  /**
   * Returns the meta object for class '{@link xtext.towerDefense.Vague <em>Vague</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vague</em>'.
   * @see xtext.towerDefense.Vague
   * @generated
   */
  EClass getVague();

  /**
   * Returns the meta object for the reference list '{@link xtext.towerDefense.Vague#getMobiles <em>Mobiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Mobiles</em>'.
   * @see xtext.towerDefense.Vague#getMobiles()
   * @see #getVague()
   * @generated
   */
  EReference getVague_Mobiles();

  /**
   * Returns the meta object for the reference list '{@link xtext.towerDefense.Vague#getObstacles <em>Obstacles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Obstacles</em>'.
   * @see xtext.towerDefense.Vague#getObstacles()
   * @see #getVague()
   * @generated
   */
  EReference getVague_Obstacles();

  /**
   * Returns the meta object for the attribute '{@link xtext.towerDefense.Vague#getGainVictoire <em>Gain Victoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gain Victoire</em>'.
   * @see xtext.towerDefense.Vague#getGainVictoire()
   * @see #getVague()
   * @generated
   */
  EAttribute getVague_GainVictoire();

  /**
   * Returns the meta object for enum '{@link xtext.towerDefense.TYPE_TERRAIN <em>TYPE TERRAIN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TYPE TERRAIN</em>'.
   * @see xtext.towerDefense.TYPE_TERRAIN
   * @generated
   */
  EEnum getTYPE_TERRAIN();

  /**
   * Returns the meta object for enum '{@link xtext.towerDefense.Difficulte <em>Difficulte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Difficulte</em>'.
   * @see xtext.towerDefense.Difficulte
   * @generated
   */
  EEnum getDifficulte();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TowerDefenseFactory getTowerDefenseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.JeuImpl <em>Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.JeuImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getJeu()
     * @generated
     */
    EClass JEU = eINSTANCE.getJeu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JEU__NAME = eINSTANCE.getJeu_Name();

    /**
     * The meta object literal for the '<em><b>Parties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JEU__PARTIES = eINSTANCE.getJeu_Parties();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.PartieImpl <em>Partie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.PartieImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getPartie()
     * @generated
     */
    EClass PARTIE = eINSTANCE.getPartie();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTIE__NAME = eINSTANCE.getPartie_Name();

    /**
     * The meta object literal for the '<em><b>Parties Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTIE__PARTIES_ELEMENTS = eINSTANCE.getPartie_PartiesElements();

    /**
     * The meta object literal for the '<em><b>Niveaux</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTIE__NIVEAUX = eINSTANCE.getPartie_Niveaux();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.PartieElementImpl <em>Partie Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.PartieElementImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getPartieElement()
     * @generated
     */
    EClass PARTIE_ELEMENT = eINSTANCE.getPartieElement();

    /**
     * The meta object literal for the '<em><b>Obstacle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTIE_ELEMENT__OBSTACLE = eINSTANCE.getPartieElement_Obstacle();

    /**
     * The meta object literal for the '<em><b>Mobile</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTIE_ELEMENT__MOBILE = eINSTANCE.getPartieElement_Mobile();

    /**
     * The meta object literal for the '<em><b>Projectile</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTIE_ELEMENT__PROJECTILE = eINSTANCE.getPartieElement_Projectile();

    /**
     * The meta object literal for the '<em><b>Nature</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTIE_ELEMENT__NATURE = eINSTANCE.getPartieElement_Nature();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.EnergieImpl <em>Energie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.EnergieImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getEnergie()
     * @generated
     */
    EClass ENERGIE = eINSTANCE.getEnergie();

    /**
     * The meta object literal for the '<em><b>Infini</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGIE__INFINI = eINSTANCE.getEnergie_Infini();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENERGIE__VALEUR = eINSTANCE.getEnergie_Valeur();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.ObstacleImpl <em>Obstacle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.ObstacleImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getObstacle()
     * @generated
     */
    EClass OBSTACLE = eINSTANCE.getObstacle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBSTACLE__NAME = eINSTANCE.getObstacle_Name();

    /**
     * The meta object literal for the '<em><b>Campement</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLE__CAMPEMENT = eINSTANCE.getObstacle_Campement();

    /**
     * The meta object literal for the '<em><b>Quantite Energie Max</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLE__QUANTITE_ENERGIE_MAX = eINSTANCE.getObstacle_QuantiteEnergieMax();

    /**
     * The meta object literal for the '<em><b>Quantite Energie Courant</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLE__QUANTITE_ENERGIE_COURANT = eINSTANCE.getObstacle_QuantiteEnergieCourant();

    /**
     * The meta object literal for the '<em><b>Ponts Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLE__PONTS_ACTION = eINSTANCE.getObstacle_PontsAction();

    /**
     * The meta object literal for the '<em><b>Tactique</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLE__TACTIQUE = eINSTANCE.getObstacle_Tactique();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.TactiqueImpl <em>Tactique</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.TactiqueImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTactique()
     * @generated
     */
    EClass TACTIQUE = eINSTANCE.getTactique();

    /**
     * The meta object literal for the '<em><b>Proche</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TACTIQUE__PROCHE = eINSTANCE.getTactique_Proche();

    /**
     * The meta object literal for the '<em><b>Faible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TACTIQUE__FAIBLE = eINSTANCE.getTactique_Faible();

    /**
     * The meta object literal for the '<em><b>Fort</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TACTIQUE__FORT = eINSTANCE.getTactique_Fort();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.MobileImpl <em>Mobile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.MobileImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getMobile()
     * @generated
     */
    EClass MOBILE = eINSTANCE.getMobile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOBILE__NAME = eINSTANCE.getMobile_Name();

    /**
     * The meta object literal for the '<em><b>Force</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOBILE__FORCE = eINSTANCE.getMobile_Force();

    /**
     * The meta object literal for the '<em><b>Volume</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOBILE__VOLUME = eINSTANCE.getMobile_Volume();

    /**
     * The meta object literal for the '<em><b>Num Vague</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOBILE__NUM_VAGUE = eINSTANCE.getMobile_NumVague();

    /**
     * The meta object literal for the '<em><b>Case Entree</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOBILE__CASE_ENTREE = eINSTANCE.getMobile_CaseEntree();

    /**
     * The meta object literal for the '<em><b>Case Sortie</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOBILE__CASE_SORTIE = eINSTANCE.getMobile_CaseSortie();

    /**
     * The meta object literal for the '<em><b>Quantite Energie Max</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOBILE__QUANTITE_ENERGIE_MAX = eINSTANCE.getMobile_QuantiteEnergieMax();

    /**
     * The meta object literal for the '<em><b>Quantite Energie Courant</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOBILE__QUANTITE_ENERGIE_COURANT = eINSTANCE.getMobile_QuantiteEnergieCourant();

    /**
     * The meta object literal for the '<em><b>Points Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOBILE__POINTS_ACTION = eINSTANCE.getMobile_PointsAction();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.ProjectileImpl <em>Projectile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.ProjectileImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getProjectile()
     * @generated
     */
    EClass PROJECTILE = eINSTANCE.getProjectile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTILE__NAME = eINSTANCE.getProjectile_Name();

    /**
     * The meta object literal for the '<em><b>Portee</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTILE__PORTEE = eINSTANCE.getProjectile_Portee();

    /**
     * The meta object literal for the '<em><b>Masse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTILE__MASSE = eINSTANCE.getProjectile_Masse();

    /**
     * The meta object literal for the '<em><b>Vitesse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTILE__VITESSE = eINSTANCE.getProjectile_Vitesse();

    /**
     * The meta object literal for the '<em><b>Case</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTILE__CASE = eINSTANCE.getProjectile_Case();

    /**
     * The meta object literal for the '<em><b>Cible</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTILE__CIBLE = eINSTANCE.getProjectile_Cible();

    /**
     * The meta object literal for the '<em><b>Degat</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTILE__DEGAT = eINSTANCE.getProjectile_Degat();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.NatureTerrainImpl <em>Nature Terrain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.NatureTerrainImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getNatureTerrain()
     * @generated
     */
    EClass NATURE_TERRAIN = eINSTANCE.getNatureTerrain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NATURE_TERRAIN__NAME = eINSTANCE.getNatureTerrain_Name();

    /**
     * The meta object literal for the '<em><b>Volume</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NATURE_TERRAIN__VOLUME = eINSTANCE.getNatureTerrain_Volume();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NATURE_TERRAIN__TYPE = eINSTANCE.getNatureTerrain_Type();

    /**
     * The meta object literal for the '<em><b>Fatigue</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NATURE_TERRAIN__FATIGUE = eINSTANCE.getNatureTerrain_Fatigue();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.NiveauImpl <em>Niveau</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.NiveauImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getNiveau()
     * @generated
     */
    EClass NIVEAU = eINSTANCE.getNiveau();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NIVEAU__NAME = eINSTANCE.getNiveau_Name();

    /**
     * The meta object literal for the '<em><b>Difficulte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NIVEAU__DIFFICULTE = eINSTANCE.getNiveau_Difficulte();

    /**
     * The meta object literal for the '<em><b>Duree Pause</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NIVEAU__DUREE_PAUSE = eINSTANCE.getNiveau_DureePause();

    /**
     * The meta object literal for the '<em><b>Argent</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NIVEAU__ARGENT = eINSTANCE.getNiveau_Argent();

    /**
     * The meta object literal for the '<em><b>Mob Sortis Limite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NIVEAU__MOB_SORTIS_LIMITE = eINSTANCE.getNiveau_MobSortisLimite();

    /**
     * The meta object literal for the '<em><b>Terrain</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NIVEAU__TERRAIN = eINSTANCE.getNiveau_Terrain();

    /**
     * The meta object literal for the '<em><b>Vagues</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NIVEAU__VAGUES = eINSTANCE.getNiveau_Vagues();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.TerrainDeJeuImpl <em>Terrain De Jeu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.TerrainDeJeuImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTerrainDeJeu()
     * @generated
     */
    EClass TERRAIN_DE_JEU = eINSTANCE.getTerrainDeJeu();

    /**
     * The meta object literal for the '<em><b>Damier</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERRAIN_DE_JEU__DAMIER = eINSTANCE.getTerrainDeJeu_Damier();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.DamierImpl <em>Damier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.DamierImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getDamier()
     * @generated
     */
    EClass DAMIER = eINSTANCE.getDamier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DAMIER__NAME = eINSTANCE.getDamier_Name();

    /**
     * The meta object literal for the '<em><b>Nb Lignes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DAMIER__NB_LIGNES = eINSTANCE.getDamier_NbLignes();

    /**
     * The meta object literal for the '<em><b>Nb Colonnes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DAMIER__NB_COLONNES = eINSTANCE.getDamier_NbColonnes();

    /**
     * The meta object literal for the '<em><b>Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DAMIER__CASES = eINSTANCE.getDamier_Cases();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.CaseImpl <em>Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.CaseImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getCase()
     * @generated
     */
    EClass CASE = eINSTANCE.getCase();

    /**
     * The meta object literal for the '<em><b>I</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CASE__I = eINSTANCE.getCase_I();

    /**
     * The meta object literal for the '<em><b>J</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CASE__J = eINSTANCE.getCase_J();

    /**
     * The meta object literal for the '<em><b>Nature Terrain</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE__NATURE_TERRAIN = eINSTANCE.getCase_NatureTerrain();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.impl.VagueImpl <em>Vague</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.impl.VagueImpl
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getVague()
     * @generated
     */
    EClass VAGUE = eINSTANCE.getVague();

    /**
     * The meta object literal for the '<em><b>Mobiles</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAGUE__MOBILES = eINSTANCE.getVague_Mobiles();

    /**
     * The meta object literal for the '<em><b>Obstacles</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAGUE__OBSTACLES = eINSTANCE.getVague_Obstacles();

    /**
     * The meta object literal for the '<em><b>Gain Victoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAGUE__GAIN_VICTOIRE = eINSTANCE.getVague_GainVictoire();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.TYPE_TERRAIN <em>TYPE TERRAIN</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.TYPE_TERRAIN
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getTYPE_TERRAIN()
     * @generated
     */
    EEnum TYPE_TERRAIN = eINSTANCE.getTYPE_TERRAIN();

    /**
     * The meta object literal for the '{@link xtext.towerDefense.Difficulte <em>Difficulte</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.towerDefense.Difficulte
     * @see xtext.towerDefense.impl.TowerDefensePackageImpl#getDifficulte()
     * @generated
     */
    EEnum DIFFICULTE = eINSTANCE.getDifficulte();

  }

} //TowerDefensePackage
