/**
 * generated by Xtext 2.12.0
 */
package xtext.towerDefense;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xtext.towerDefense.TowerDefensePackage
 * @generated
 */
public interface TowerDefenseFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TowerDefenseFactory eINSTANCE = xtext.towerDefense.impl.TowerDefenseFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Jeu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jeu</em>'.
   * @generated
   */
  Jeu createJeu();

  /**
   * Returns a new object of class '<em>Partie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Partie</em>'.
   * @generated
   */
  Partie createPartie();

  /**
   * Returns a new object of class '<em>Partie Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Partie Element</em>'.
   * @generated
   */
  PartieElement createPartieElement();

  /**
   * Returns a new object of class '<em>Niveau</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Niveau</em>'.
   * @generated
   */
  Niveau createNiveau();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TowerDefensePackage getTowerDefensePackage();

} //TowerDefenseFactory
